=== canercandan/iot-project/ceg/test/schema.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   targetNamespace="http://www.ionlythink.com"
	   xmlns="http://www.ionlythink.com"
	   elementFormDefault="qualified">

  <!-- definition of simple elements -->

  <!-- definition of attributes -->

  <xs:element name="style">
    <xs:complexType>
      <xs:attribute name="visible" type="xs:boolean" default="true"/>
      <xs:attribute name="opacity" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="imagePath" type="xs:anyURI"/>
      <xs:attribute name="text" type="xs:string"/>
      <xs:attribute name="textFont" type="xs:string"/>
      <xs:attribute name="colorOnFocus" type="xs:string"/>
      <xs:attribute name="colorOnBlur" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="boxType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="custom"/>
      <xs:enumeration value="default"/>
      <xs:enumeration value="menuitem"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Cancel"/>
      <xs:enumeration value="Click"/>
      <xs:enumeration value="Close"/>
      <xs:enumeration value="ExecMenu"/>
      <xs:enumeration value="ExecProcess"/>
      <xs:enumeration value="Keyboard"/>
      <xs:enumeration value="MoveAction"/>
      <xs:enumeration value="PopMenu"/>
      <xs:enumeration value="Quit"/>
      <xs:enumeration value="Read"/>
      <xs:enumeration value="Valid"/>
      <xs:enumeration value="Write"/>
      <xs:enumeration value="Zoom"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- definition of complex elements -->

  <!-- <xs:element name="children"> -->
  <!--   <xs:complexType> -->
  <!--     <xs:element ref="box" maxOccurs="unbounded"/> -->
  <!--     <xs:any minOccurs="0" maxOccurs="unbounded"/> -->
  <!--   </xs:complexType> -->
  <!-- </xs:element> -->

  <xs:element name="action">
    <xs:complexType>
      <xs:attribute name="id" type="idType"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>

      <!-- <xs:attribute name="unix:path" type="xs:string" use="optional"/> -->
      <!-- <xs:attribute name="win:path" type="xs:string" use="optional"/> -->
      <!-- <xs:attribute name="mac:path" type="xs:string" use="optional"/> -->
      <xs:attribute name="path" type="xs:string" use="optional"/>
      <xs:attribute name="unix-path" type="xs:string" use="optional"/>
      <xs:attribute name="win-path" type="xs:string" use="optional"/>
      <xs:attribute name="mac-path" type="xs:string" use="optional"/>

    </xs:complexType>
  </xs:element>

  <xs:element name="box">
    <xs:complexType>
      <xs:attribute name="width" type="xs:nonNegativeInteger"/>
      <xs:attribute name="height" type="xs:nonNegativeInteger"/>
      <xs:attribute name="x" type="xs:nonNegativeInteger"/>
      <xs:attribute name="y" type="xs:nonNegativeInteger"/>

      <!-- <xs:element ref="children"/> -->
    </xs:complexType>
  </xs:element>

  <xs:element name="boxes">
    <xs:complexType>
      <xs:sequence>
	<xs:element ref="box" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== canercandan/iot-project/ceg/share/ceg/config/menus/ApplicationMenu.xml
<boxes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.ionlythink.com"
      xsi:schemaLocation="http://www.ionlythink.com schema.xsd"
      id="Application">
  <box type="2" x="750" y="1" height="80" width="240">
    <action id="ExecMenu">
      <action id="ExecProcess" name="Firefox" time="5000"
	      path="default_path"
	      unix-path="firefox"
	      win-path="C:\Program Files\Mozilla Firefox\firefox.exe"
	      mac-path="unknown"
	      />
    </action>
    <style fontSize="12" opacity="1" text="Firefox" imagePath=":images/software/firefox.png" rounded="true"/>
  </box>

  <box type="2" x="750" y="101" height="80" width="240">
    <action id="ExecMenu">
      <action id="ExecProcess" time="5000"
	      path="C:\Program Files\Windows Media Player/wmplayer.exe"
	      win-path="C:\Program Files\Windows Media Player/wmplayer.exe"
	      />
    </action>
    <style fontSize="12" opacity="1" text="Windows Media Player" imagePath=":images/software/wmp.png" rounded="true"/>
  </box>

  <box type="2" x="750" y="201" height="80" width="240">
    <action id="ExecMenu">
      <action id="ExecProcess" time="3000"
	      path="C:\Program Files\Notepad++\notepad++.exe"
	      win-path="C:\Program Files\Notepad++\notepad++.exe"
	      />
    </action>
    <style fontSize="12" opacity="1" text="Notepad++" imagePath=":images/software/notepad++.png" rounded="true"/>
  </box>

  <box type="2" x="750" y="301" height="80" width="240">
    <action id="ExecMenu">
      <action id="ExecProcess" time="1000"
	      unix-path="gnome-calculator"
	      win-path="C:\WINDOWS\system32\calc.exe"
	      />
    </action>
    <style fontSize="12" opacity="1" text="Calculator" fr-text="Calculatrice" imagePath=":images/software/calc.png" rounded="true"/>
  </box>

  <box type="2" x="750" y="401" height="80" width="240">
    <action id="ExecMenu">
      <action id="Cancel"/>
    </action>
    <style fontSize="12" opacity="1" text="Back" fr-text="Retour" imagePath=":images/menu/cancel.png" rounded="true"/>
  </box>

</boxes>

=== canercandan/iot-project/ceg/share/ceg/config/boxes/Firefox.xml
<boxes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.ionlythink.com"
       xsi:schemaLocation="http://www.ionlythink.com schema.xsd"
       id="firefox"
       resolution-x="0"
       resolution-y="0"
       resolution-width="1024"
       resolution-height="768">
 <box width="191" x="1" y="45" height="30" type="1">
  <action id="Zoom" isZoom="1"/>
  <style imagePath="" opacity="0.5" rounded="0" focusColor="red" blurColor="blue" text="" textColor="black"/>
  <children>
   <box width="38" x="2" y="42" height="36" type="1">
    <action type="0" id="Click"/>
    <style imagePath="" opacity="0.5" rounded="1" focusColor="red" blurColor="blue" text="" textColor="black"/>
   </box>
   <box width="38" x="42" y="42" height="36" type="1">
    <action type="0" id="Click"/>
    <style imagePath="" opacity="0.5" rounded="1" focusColor="red" blurColor="blue" text="" textColor="black"/>
   </box>
   <box width="38" x="82" y="42" height="36" type="1">
    <action type="0" id="Click"/>
    <style imagePath="" opacity="0.5" rounded="1" focusColor="red" blurColor="blue" text="" textColor="black"/>
   </box>
   <box width="27" x="123" y="42" height="36" type="1">
    <action type="0" id="Click"/>
    <style imagePath="" opacity="0.5" rounded="1" focusColor="red" blurColor="blue" text="" textColor="black"/>
   </box>
   <box width="33" x="156" y="42" height="36" type="1">
    <action type="0" id="Click"/>
    <style imagePath="" opacity="0.5" rounded="1" focusColor="red" blurColor="blue" text="" textColor="black"/>
   </box>
  </children>
 </box>
 <box width="545" x="221" y="49" height="23" type="1">
  <action type="0" id="Click"/>
  <style imagePath="" opacity="0.5" rounded="0" focusColor="red" blurColor="blue" text="" textColor="black"/>
 </box>
 <box width="179" x="817" y="48" height="25" type="1">
  <action id="Zoom" isZoom="1"/>
  <style imagePath="" opacity="0.5" rounded="0" focusColor="red" blurColor="blue" text="" textColor="black"/>
 </box>
 <box width="1023" x="0" y="136" height="583" type="1">
  <action id="Zoom" isZoom="1"/>
  <style imagePath="" opacity="0.5" rounded="0" focusColor="red" blurColor="blue" text="" textColor="black"/>
 </box>
 <box width="367" x="2" y="21" height="19" type="1">
  <action id="Zoom" isZoom="1"/>
  <style imagePath="" opacity="0.5" rounded="0" focusColor="red" blurColor="blue" text="" textColor="black"/>
 </box>
</boxes>
